### PR TITLE
Testnet fix

### PR DESCRIPTION
**Pull request by galpHub**
### Feature

* Remove port & networkID dependent behavior between testnet/mainnet
* Remove superblock collisions
* Avoid minting errors between subsidy reduction events
* Various refactorings improving readability
* Dead code deletion

### Description

* Refactor notification signals & allow registration of interfaces
* Separate amount type from CFeeRate
* Remove redundant parameter assignments & function calls in chainparams.*
* Remove empty files masternode-budget.*
* Extract fee-related functionality out of transaction class
* Remove unused coinage function
* Move block reward struct into own file
* Move block & superblock subsidies into separate file
* Move superblock rewards directly into the block subsidies - removing indirect computation
* Repair main tests to compute correct minting calculations
* Move check for masternode reward into wallet instead of UTXO class
* Remove unused functions from transaction.*
* Remove redundant headers from spork.h
* Bump testnet lottery and treasury cycles to resemble mainnet more closely

### Notes

* No additional notes at this time

### CODE REVIEW

**Comment by galpHub** [comment]
Just noticed a problem with one of the files. Will be fixing it shortly

**Comment by galpHub** [comment]
> What are the modifications to fees and priorities? Anything that should be in the documentation?
> I see several comments (//) with the word BITCOIN but the folders are all DIVI ... and you did a PR the other day with references to DIVI ... so just on the notes, maybe we can run a find replace for those at some point (sent to Voice for tasking)
> 
> AWESOME job on the code ... so easy to read! This is self-documenting code ... you can read WTF is happening ... in-line! Thanks!

No modifications at all. Purely refactoring => Functionality preserving, Readability & Modularity improvements

**Comment by galpHub** [comment]
@Encke are you finding those references are pure comments or as the header guards or is it in the build files or maybe somewhere else? The header guards are easiest to fix (though they functionally change nothing).

**Comment by Encke** [comment]
Just in the comments on the top / bottom of the file, not even normal ... like block coding.

I can help to search if you need ... this week ... its not a deal at al .. I just saw all the updates last week and in this PR in the files I reveiwed there were a lot :)

**Pull request merged**
