### PR TITLE
Create reproducible Dockerfile build

### PR DESCRIPTION
**Pull request by galpHub**
This will ideally facilitate testing hard-fork backwards compatibility

### CODE REVIEW

**Comment by 99darwin** [comment]
This looks fine to me. Also requesting @ChrisCates or @Encke for a secondary review.

**Comment by galpHub** [comment]
For reference: https://github.com/PIVX-Project/PIVX/issues/149

**Comment by ChrisCates** [comment]
Let's get this passing on Travis CI.
I will send an update in a bit one second.

**Comment by galpHub** [comment]
> We should have a travis.yml file
Added to the base directory of the repo

**Comment by ChrisCates** [comment]
@galpHub, okay sweet.

Few more things!

1. need to verify it passes on https://travis-ci.org/ You'll be able to test it on your own repo and branch.

2. Should put a travis-ci badge in the README.md!

**Comment by galpHub** [comment]
> @galpHub, okay sweet.
> 
> Few more things!
> 
> 1. need to verify it passes on https://travis-ci.org/ You'll be able to test it on your own repo and branch.
> 2. Should put a travis-ci badge in the README.md!

Done

**Comment by galpHub** [comment]
Closing for now to break up into two PRs

**Pull request closed without merging**
