### PR TITLE
Clearly explain BTC droplet construction with mounted volume

### PR DESCRIPTION
**Pull request by galpHub**
Running a bitcoin node on Digital Ocean with a mounted volume and how to use the cli

### CODE REVIEW

**Comment by ChrisCates** [comment]
@galpHub, I've added improved formatting and readability to the markdown file. Feel free to review the changes I made and make changes if necessary.

**Comment by ChrisCates** [comment]
Also, a good idea when creating a pull request is to create a new branch specifying your changes.

```bash
git checkout posv3
git checkout -b @galpHub/docs
### Make changes and then commit
git push origin @galphub/docs
```

And then create a pull request from that branch.

**Comment by galpHub** [comment]
> Also, a good idea when creating a pull request is to create a new branch specifying your changes.
> 
> ```shell
> git checkout posv3
> git checkout -b @galpHub/docs
> ### Make changes and then commit
> git push origin @galphub/docs
> ```
> 
> And then create a pull request from that branch.

Sounds good :D 🗡

**Comment by ChrisCates** [comment]
Great, I've merged it into `posv3`. Let me know if you have any questions or concerns!

**Pull request merged**
